<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\UnidadAdministrativa;

class UnidadesAdministrativasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $unidades = [
            ['id' => '1', 'nombre' => 'ASESORIA LEGAL', 'codigo' => '0002'],
            ['id' => '2', 'nombre' => 'DELEGACION DE DISTRITO CAPITAL', 'codigo' => '0125'],
            ['id' => '3', 'nombre' => 'DELEGACION ESTADAL AMAZONAS', 'codigo' => '0390'],
            ['id' => '4', 'nombre' => 'DELEGACION ESTADAL ANZOATEGUI', 'codigo' => '0334'],
            ['id' => '5', 'nombre' => 'DELEGACION ESTADAL APURE', 'codigo' => '0208'],
            ['id' => '6', 'nombre' => 'DELEGACION ESTADAL ARAGUA', 'codigo' => '0162'],
            ['id' => '7', 'nombre' => 'DELEGACION ESTADAL BARINAS', 'codigo' => '0216'],
            ['id' => '8', 'nombre' => 'DELEGACION ESTADAL BOLIVAR', 'codigo' => '0372'],
            ['id' => '9', 'nombre' => 'DELEGACION ESTADAL CARABOBO', 'codigo' => '0182'],
            ['id' => '10', 'nombre' => 'DELEGACION ESTADAL COJEDES', 'codigo' => '0232'],
            ['id' => '11', 'nombre' => 'DELEGACION ESTADAL DELTA AMACURO', 'codigo' => '0386'],
            ['id' => '12', 'nombre' => 'DELEGACION ESTADAL FALCON', 'codigo' => '0252'],
            ['id' => '13', 'nombre' => 'DELEGACION ESTADAL GUARICO', 'codigo' => '0238'],
            ['id' => '14', 'nombre' => 'DELEGACION ESTADAL LA GUAIRA', 'codigo' => '0159'],
            ['id' => '15', 'nombre' => 'DELEGACION ESTADAL LARA', 'codigo' => '0262'],
            ['id' => '16', 'nombre' => 'DELEGACION ESTADAL MERIDA', 'codigo' => '0312'],
            ['id' => '17', 'nombre' => 'DELEGACION ESTADAL MIRANDA', 'codigo' => '0144'],
            ['id' => '18', 'nombre' => 'DELEGACION ESTADAL MONAGAS', 'codigo' => '0360'],
            ['id' => '19', 'nombre' => 'DELEGACION ESTADAL NUEVA ESPARTA', 'codigo' => '0394'],
            ['id' => '20', 'nombre' => 'DELEGACION ESTADAL PORTUGUESA', 'codigo' => '0226'],
            ['id' => '21', 'nombre' => 'DELEGACION ESTADAL SUCRE', 'codigo' => '0350'],
            ['id' => '22', 'nombre' => 'DELEGACION ESTADAL TACHIRA', 'codigo' => '0320'],
            ['id' => '23', 'nombre' => 'DELEGACION ESTADAL TRUJILLO', 'codigo' => '0302'],
            ['id' => '24', 'nombre' => 'DELEGACION ESTADAL YARACUY', 'codigo' => '0198'],
            ['id' => '25', 'nombre' => 'DELEGACION ESTADAL ZULIA', 'codigo' => '0276'],
            ['id' => '26', 'nombre' => 'DELEGACION MUNICIPAL ACARIGUA', 'codigo' => '0229'],
            ['id' => '27', 'nombre' => 'DELEGACION MUNICIPAL ACHAGUAS', 'codigo' => '0213'],
            ['id' => '28', 'nombre' => 'DELEGACION MUNICIPAL ALTAGRACIA DE ORITUCO', 'codigo' => '0245'],
            ['id' => '29', 'nombre' => 'DELEGACION MUNICIPAL ANACO', 'codigo' => '0341'],
            ['id' => '30', 'nombre' => 'DELEGACION MUNICIPAL ARAGUA DE BARCELONA', 'codigo' => '0337'],
            ['id' => '31', 'nombre' => 'DELEGACION MUNICIPAL BARCELONA', 'codigo' => '0335'],
            ['id' => '32', 'nombre' => 'DELEGACION MUNICIPAL BARINAS', 'codigo' => '0217'],
            ['id' => '33', 'nombre' => 'DELEGACION MUNICIPAL BARQUISIMETO', 'codigo' => '0263'],
            ['id' => '34', 'nombre' => 'DELEGACION MUNICIPAL BARUTA SANTA MONICA', 'codigo' => '0142'],
            ['id' => '35', 'nombre' => 'DELEGACION MUNICIPAL BEJUMA', 'codigo' => '0189'],
            ['id' => '36', 'nombre' => 'DELEGACION MUNICIPAL BOCONO', 'codigo' => '0307'],
            ['id' => '37', 'nombre' => 'DELEGACION MUNICIPAL CAÑA DE AZUCAR', 'codigo' => '0175'],
            ['id' => '38', 'nombre' => 'DELEGACION MUNICIPAL CABIMAS', 'codigo' => '0287'],
            ['id' => '39', 'nombre' => 'DELEGACION MUNICIPAL CABUDARE', 'codigo' => '0265'],
            ['id' => '40', 'nombre' => 'DELEGACION MUNICIPAL CAGUA', 'codigo' => '0167'],
            ['id' => '41', 'nombre' => 'DELEGACION MUNICIPAL CAICARA DEL ORINOCO', 'codigo' => '0381'],
            ['id' => '42', 'nombre' => 'DELEGACION MUNICIPAL CAJA SECA', 'codigo' => '0289'],
            ['id' => '43', 'nombre' => 'DELEGACION MUNICIPAL CALABOZO', 'codigo' => '0243'],
            ['id' => '44', 'nombre' => 'DELEGACION MUNICIPAL CAMAGUAN', 'codigo' => '0404'],
            ['id' => '45', 'nombre' => 'DELEGACION MUNICIPAL CAMATAGUA', 'codigo' => '0165'],
            ['id' => '46', 'nombre' => 'DELEGACION MUNICIPAL CARIPE', 'codigo' => '0363'],
            ['id' => '47', 'nombre' => 'DELEGACION MUNICIPAL CARIPITO', 'codigo' => '0365'],
            ['id' => '48', 'nombre' => 'DELEGACION MUNICIPAL CARLOS ARVELO', 'codigo' => '0191'],
            ['id' => '49', 'nombre' => 'DELEGACION MUNICIPAL CARORA', 'codigo' => '0269'],
            ['id' => '50', 'nombre' => 'DELEGACION MUNICIPAL CARUPANO', 'codigo' => '0353'],
            ['id' => '51', 'nombre' => 'DELEGACION MUNICIPAL CAUCAGUA', 'codigo' => '0153'],
            ['id' => '52', 'nombre' => 'DELEGACION MUNICIPAL CHIVACOA', 'codigo' => '0201'],
            ['id' => '53', 'nombre' => 'DELEGACION MUNICIPAL CHURUGUARA', 'codigo' => '0402'],
            ['id' => '54', 'nombre' => 'DELEGACION MUNICIPAL CIUDAD BOLIVAR', 'codigo' => '0373'],
            ['id' => '55', 'nombre' => 'DELEGACION MUNICIPAL CIUDAD GUAYANA', 'codigo' => '0375'],
            ['id' => '56', 'nombre' => 'DELEGACION MUNICIPAL CIUDAD OJEDA', 'codigo' => '0291'],
            ['id' => '57', 'nombre' => 'DELEGACION MUNICIPAL COLONIA TOVAR', 'codigo' => '0179'],
            ['id' => '58', 'nombre' => 'DELEGACION MUNICIPAL CORO', 'codigo' => '0253'],
            ['id' => '59', 'nombre' => 'DELEGACION MUNICIPAL CUMANA', 'codigo' => '0351'],
            ['id' => '60', 'nombre' => 'DELEGACION MUNICIPAL CUMANACOA', 'codigo' => '0357'],
            ['id' => '61', 'nombre' => 'DELEGACION MUNICIPAL DABAJURO', 'codigo' => '0255'],
            ['id' => '62', 'nombre' => 'DELEGACION MUNICIPAL EL MOJAN', 'codigo' => '0297'],
            ['id' => '63', 'nombre' => 'DELEGACION MUNICIPAL EL SOMBRERO', 'codigo' => '0249'],
            ['id' => '64', 'nombre' => 'DELEGACION MUNICIPAL EL TIGRE', 'codigo' => '0343'],
            ['id' => '65', 'nombre' => 'DELEGACION MUNICIPAL EL TOCUYO', 'codigo' => '0273'],
            ['id' => '66', 'nombre' => 'DELEGACION MUNICIPAL EL VIGIA', 'codigo' => '0317'],
            ['id' => '67', 'nombre' => 'DELEGACION MUNICIPAL GUANARE', 'codigo' => '0227'],
            ['id' => '68', 'nombre' => 'DELEGACION MUNICIPAL GUARENAS', 'codigo' => '0147'],
            ['id' => '69', 'nombre' => 'DELEGACION MUNICIPAL GUASDUALITO', 'codigo' => '0211'],
            ['id' => '70', 'nombre' => 'DELEGACION MUNICIPAL GUIRIA', 'codigo' => '0355'],
            ['id' => '71', 'nombre' => 'DELEGACION MUNICIPAL HIGUEROTE', 'codigo' => '0149'],
            ['id' => '72', 'nombre' => 'DELEGACION MUNICIPAL JUAN GRIEGO', 'codigo' => '0397'],
            ['id' => '73', 'nombre' => 'DELEGACION MUNICIPAL LA FRIA', 'codigo' => '0325'],
            ['id' => '74', 'nombre' => 'DELEGACION MUNICIPAL LA GRITA', 'codigo' => '0323'],
            ['id' => '75', 'nombre' => 'DELEGACION MUNICIPAL LA GUAIRA', 'codigo' => '0160'],
            ['id' => '76', 'nombre' => 'DELEGACION MUNICIPAL LA VICTORIA', 'codigo' => '0171'],
            ['id' => '77', 'nombre' => 'DELEGACION MUNICIPAL LAS ACACIAS', 'codigo' => '0185'],
            ['id' => '78', 'nombre' => 'DELEGACION MUNICIPAL LAS TEJERIAS', 'codigo' => '0177'],
            ['id' => '79', 'nombre' => 'DELEGACION MUNICIPAL LIBERTADOR BARUTA CHACAO', 'codigo' => '0138'],
            ['id' => '80', 'nombre' => 'DELEGACION MUNICIPAL LIBERTADOR CARICUAO', 'codigo' => '0126'],
            ['id' => '81', 'nombre' => 'DELEGACION MUNICIPAL LIBERTADOR EL PARAISO', 'codigo' => '0128'],
            ['id' => '82', 'nombre' => 'DELEGACION MUNICIPAL LIBERTADOR EL VALLE', 'codigo' => '0130'],
            ['id' => '83', 'nombre' => 'DELEGACION MUNICIPAL LIBERTADOR LA VEGA', 'codigo' => '0132'],
            ['id' => '84', 'nombre' => 'DELEGACION MUNICIPAL LIBERTADOR OESTE', 'codigo' => '0134'],
            ['id' => '85', 'nombre' => 'DELEGACION MUNICIPAL LIBERTADOR SIMON RODRIGUEZ', 'codigo' => '0136'],
            ['id' => '86', 'nombre' => 'DELEGACION MUNICIPAL LOS TEQUES', 'codigo' => '0145'],
            ['id' => '87', 'nombre' => 'DELEGACION MUNICIPAL MACHIQUES', 'codigo' => '0285'],
            ['id' => '88', 'nombre' => 'DELEGACION MUNICIPAL MARACAIBO', 'codigo' => '0277'],
            ['id' => '89', 'nombre' => 'DELEGACION MUNICIPAL MARACAY', 'codigo' => '0163'],
            ['id' => '90', 'nombre' => 'DELEGACION MUNICIPAL MARIÑO', 'codigo' => '0169'],
            ['id' => '91', 'nombre' => 'DELEGACION MUNICIPAL MARIARA', 'codigo' => '0187'],
            ['id' => '92', 'nombre' => 'DELEGACION MUNICIPAL MATURIN', 'codigo' => '0361'],
            ['id' => '93', 'nombre' => 'DELEGACION MUNICIPAL MENE GRANDE', 'codigo' => '0281'],
            ['id' => '94', 'nombre' => 'DELEGACION MUNICIPAL MERIDA', 'codigo' => '0313'],
            ['id' => '95', 'nombre' => 'DELEGACION MUNICIPAL NIRGUA', 'codigo' => '0205'],
            ['id' => '96', 'nombre' => 'DELEGACION MUNICIPAL OCUMARE DEL TUY', 'codigo' => '0155'],
            ['id' => '97', 'nombre' => 'DELEGACION MUNICIPAL PARAGUAIPOA', 'codigo' => '0293'],
            ['id' => '98', 'nombre' => 'DELEGACION MUNICIPAL PARIAGUAN', 'codigo' => '0347'],
            ['id' => '99', 'nombre' => 'DELEGACION MUNICIPAL PORLAMAR', 'codigo' => '0395'],
            ['id' => '100', 'nombre' => 'DELEGACION MUNICIPAL PUERTO AYACUCHO', 'codigo' => '0391'],
            ['id' => '101', 'nombre' => 'DELEGACION MUNICIPAL PUERTO CABELLO', 'codigo' => '0193'],
            ['id' => '102', 'nombre' => 'DELEGACION MUNICIPAL PUERTO LA CRUZ', 'codigo' => '0345'],
            ['id' => '103', 'nombre' => 'DELEGACION MUNICIPAL PUERTO PIRITU', 'codigo' => '0339'],
            ['id' => '104', 'nombre' => 'DELEGACION MUNICIPAL PUERTOS DE ALTAGRACIA', 'codigo' => '0279'],
            ['id' => '105', 'nombre' => 'DELEGACION MUNICIPAL PUNTA DE MATA', 'codigo' => '0367'],
            ['id' => '106', 'nombre' => 'DELEGACION MUNICIPAL PUNTA DE PIEDRA', 'codigo' => '0399'],
            ['id' => '107', 'nombre' => 'DELEGACION MUNICIPAL PUNTO FIJO', 'codigo' => '0257'],
            ['id' => '108', 'nombre' => 'DELEGACION MUNICIPAL QUIBOR', 'codigo' => '0271'],
            ['id' => '109', 'nombre' => 'DELEGACION MUNICIPAL RUBIO', 'codigo' => '0327'],
            ['id' => '110', 'nombre' => 'DELEGACION MUNICIPAL SABANA DE MENDOZA', 'codigo' => '0310'],
            ['id' => '111', 'nombre' => 'DELEGACION MUNICIPAL SABANETA', 'codigo' => '0221'],
            ['id' => '112', 'nombre' => 'DELEGACION MUNICIPAL SAN ANTONIO DEL TACHIRA', 'codigo' => '0329'],
            ['id' => '113', 'nombre' => 'DELEGACION MUNICIPAL SAN CARLOS DE COJEDES', 'codigo' => '0233'],
            ['id' => '114', 'nombre' => 'DELEGACION MUNICIPAL SAN CARLOS DEL ZULIA', 'codigo' => '0299'],
            ['id' => '115', 'nombre' => 'DELEGACION MUNICIPAL SAN CRISTOBAL', 'codigo' => '0321'],
            ['id' => '116', 'nombre' => 'DELEGACION MUNICIPAL SAN FELIPE', 'codigo' => '0199'],
            ['id' => '117', 'nombre' => 'DELEGACION MUNICIPAL SAN FERNANDO DE APURE', 'codigo' => '0209'],
            ['id' => '118', 'nombre' => 'DELEGACION MUNICIPAL SAN FRANCISCO', 'codigo' => '0295'],
            ['id' => '119', 'nombre' => 'DELEGACION MUNICIPAL SAN JOSE DE BARLOVENTO', 'codigo' => '0151'],
            ['id' => '120', 'nombre' => 'DELEGACION MUNICIPAL SAN JUAN DE LOS MORROS', 'codigo' => '0239'],
            ['id' => '121', 'nombre' => 'DELEGACION MUNICIPAL SAN JUAN LARA', 'codigo' => '0267'],
            ['id' => '122', 'nombre' => 'DELEGACION MUNICIPAL SANTA BARBARA DE BARINAS', 'codigo' => '0219'],
            ['id' => '123', 'nombre' => 'DELEGACION MUNICIPAL SANTA ELENA DE GUAIREN', 'codigo' => '0383'],
            ['id' => '124', 'nombre' => 'DELEGACION MUNICIPAL SANTA TERESA DEL TUY', 'codigo' => '0157'],
            ['id' => '125', 'nombre' => 'DELEGACION MUNICIPAL SOCOPO', 'codigo' => '0223'],
            ['id' => '126', 'nombre' => 'DELEGACION MUNICIPAL SUCRE EL LLANITO', 'codigo' => '0140'],
            ['id' => '127', 'nombre' => 'DELEGACION MUNICIPAL TEMBLADOR', 'codigo' => '0369'],
            ['id' => '128', 'nombre' => 'DELEGACION MUNICIPAL TINAQUILLO', 'codigo' => '0235'],
            ['id' => '129', 'nombre' => 'DELEGACION MUNICIPAL TOCUYITO', 'codigo' => '0195'],
            ['id' => '130', 'nombre' => 'DELEGACION MUNICIPAL TOVAR', 'codigo' => '0315'],
            ['id' => '131', 'nombre' => 'DELEGACION MUNICIPAL TRUJILLO', 'codigo' => '0303'],
            ['id' => '132', 'nombre' => 'DELEGACION MUNICIPAL TUCACAS', 'codigo' => '0259'],
            ['id' => '133', 'nombre' => 'DELEGACION MUNICIPAL TUCUPITA', 'codigo' => '0387'],
            ['id' => '134', 'nombre' => 'DELEGACION MUNICIPAL TUMEREMO', 'codigo' => '0377'],
            ['id' => '135', 'nombre' => 'DELEGACION MUNICIPAL UPATA', 'codigo' => '0379'],
            ['id' => '136', 'nombre' => 'DELEGACION MUNICIPAL UREÑA', 'codigo' => '0331'],
            ['id' => '137', 'nombre' => 'DELEGACION MUNICIPAL VALENCIA', 'codigo' => '0183'],
            ['id' => '138', 'nombre' => 'DELEGACION MUNICIPAL VALERA', 'codigo' => '0305'],
            ['id' => '139', 'nombre' => 'DELEGACION MUNICIPAL VALLE DE LA PASCUA', 'codigo' => '0241'],
            ['id' => '140', 'nombre' => 'DELEGACION MUNICIPAL VILLA DE CURA', 'codigo' => '0173'],
            ['id' => '141', 'nombre' => 'DELEGACION MUNICIPAL VILLA DEL ROSARIO DE PERIJA', 'codigo' => '0283'],
            ['id' => '142', 'nombre' => 'DELEGACION MUNICIPAL YARITAGUA', 'codigo' => '0203'],
            ['id' => '143', 'nombre' => 'DELEGACION MUNICIPAL ZARAZA', 'codigo' => '0247'],
            ['id' => '144', 'nombre' => 'DIRECCION DE BLOQUE DE BUSQUEDA Y APREHENSION', 'codigo' => '397'],
            ['id' => '145', 'nombre' => 'DIRECCION DE INTERVENCION Y ASALTO', 'codigo' => '0117'],
            ['id' => '146', 'nombre' => 'DIRECCION DE INVESTIGACIONES CONTRA DROGAS', 'codigo' => '0061'],
            ['id' => '147', 'nombre' => 'DIRECCION DE INVESTIGACIONES DE DELITOS CONTRA LA PROPIEDAD', 'codigo' => '0079'],
            ['id' => '148', 'nombre' => 'DIRECCION DE INVESTIGACIONES DE DELITOS CONTRA LAS PERSONAS', 'codigo' => '0057'],
            ['id' => '149', 'nombre' => 'DIRECCION DE INVESTIGACIONES DE ROBO Y HURTO DE VEHICULOS', 'codigo' => '0066'],
            ['id' => '150', 'nombre' => 'DIRECCION GENERAL', 'codigo' => '0001'],
            ['id' => '151', 'nombre' => 'DIVISION DE APOYO OPERATIVO COMUNICACIONAL', 'codigo' => '0091'],
            ['id' => '152', 'nombre' => 'DIVISION DE BUSQUEDA Y CAPTURA DE ORGANIZACIONES CRIMINALES', 'codigo' => '0092'],
            ['id' => '153', 'nombre' => 'DIVISION DE CRIMINALISTICA MUNICIPAL ACARIGUA', 'codigo' => '0230'],
            ['id' => '154', 'nombre' => 'DIVISION DE CRIMINALISTICA MUNICIPAL BARINAS', 'codigo' => '0218'],
            ['id' => '155', 'nombre' => 'DIVISION DE CRIMINALISTICA MUNICIPAL PUERTO AYACUCHO', 'codigo' => '0392'],
            ['id' => '156', 'nombre' => 'DIVISION DE CRIMINALISTICA MUNICIPAL SABANA DE MENDOZA', 'codigo' => '0310'],
            ['id' => '157', 'nombre' => 'DIVISION DE CRIMINALISTICA MUNICIPAL SAN JUAN LARA', 'codigo' => '0268'],
            ['id' => '158', 'nombre' => 'DIVISION DE CRIMINALISTICA MUNICIPAL VALLE DE LA PASCUA', 'codigo' => '0242'],
            ['id' => '159', 'nombre' => 'DIVISION DE ESTUDIOS NORMATIVOS Y OPINION JURIDICA', 'codigo' => '0004'],
            ['id' => '160', 'nombre' => 'DIVISION DE EVALUACION INTEGRAL', 'codigo' => '0018'],
            ['id' => '161', 'nombre' => 'DIVISION DE EXPERTICIAS DE VEHICULOS', 'codigo' => '0068'],
            ['id' => '162', 'nombre' => 'DIVISION DE INFORMACION POLICIAL', 'codigo' => '0095'],
            ['id' => '163', 'nombre' => 'DIVISION DE INVESTIGACIONES CONTRA DROGAS', 'codigo' => '0062'],
            ['id' => '164', 'nombre' => 'DIVISION DE INVESTIGACIONES CONTRA DROGAS EN PUERTOS, AEROPUERTOS Y FRONTERAS', 'codigo' => '0065'],
            ['id' => '165', 'nombre' => 'DIVISION DE INVESTIGACIONES CONTRA EL TERRORISMO', 'codigo' => '0076'],
            ['id' => '166', 'nombre' => 'DIVISION DE INVESTIGACIONES DE ASUNTOS INTERNOS', 'codigo' => '0007'],
            ['id' => '167', 'nombre' => 'DIVISION DE INVESTIGACIONES DE DELITOS AMBIENTALES Y MALTRATO ANIMAL', 'codigo' => '0078'],
            ['id' => '168', 'nombre' => 'DIVISION DE INVESTIGACIONES DE DELITOS CONTRA LA MUJER, NIÑO, NIÑA Y ADOLESCENTES', 'codigo' => '0059'],
            ['id' => '169', 'nombre' => 'DIVISION DE INVESTIGACIONES DE DELITOS CONTRA LA SALUD PUBLICA', 'codigo' => '0075'],
            ['id' => '170', 'nombre' => 'DIVISION DE INVESTIGACIONES DE DELITOS DE FRAUDE Y ESTAFA', 'codigo' => '0082'],
            ['id' => '171', 'nombre' => 'DIVISION DE INVESTIGACIONES DE DELITOS EN LA FUNCION PUBLICA', 'codigo' => '0074'],
            ['id' => '172', 'nombre' => 'DIVISION DE INVESTIGACIONES DE DELITOS FINANCIEROS', 'codigo' => '0084'],
            ['id' => '173', 'nombre' => 'DIVISION DE INVESTIGACIONES DE DELITOS INFORMATICOS', 'codigo' => '0080'],
            ['id' => '174', 'nombre' => 'DIVISION DE INVESTIGACIONES DE EXTORSION', 'codigo' => '0072'],
            ['id' => '175', 'nombre' => 'DIVISION DE INVESTIGACIONES DE HOMICIDOS', 'codigo' => '0058'],
            ['id' => '176', 'nombre' => 'DIVISION DE INVESTIGACIONES DE HURTO', 'codigo' => '0083'],
            ['id' => '177', 'nombre' => 'DIVISION DE INVESTIGACIONES DE HURTO DE VEHICULOS', 'codigo' => '0069'],
            ['id' => '178', 'nombre' => 'DIVISION DE INVESTIGACIONES DE LEGITIMACION DE CAPITALES', 'codigo' => '0073'],
            ['id' => '179', 'nombre' => 'DIVISION DE INVESTIGACIONES DE ROBO', 'codigo' => '0081'],
            ['id' => '180', 'nombre' => 'DIVISION DE INVESTIGACIONES DE ROBO DE VEHICULOS', 'codigo' => '0067'],
            ['id' => '181', 'nombre' => 'DIVISION DE INVESTIGACIONES DE SECUESTRO', 'codigo' => '0071'],
            ['id' => '182', 'nombre' => 'DIVISION DE INVESTIGACIONES DE TRATA DE PERSONAS', 'codigo' => '0077'],
            ['id' => '183', 'nombre' => 'DIVISION DE INVESTIGACIONES DE VICTIMAS ESPECIALES', 'codigo' => '0060'],
            ['id' => '184', 'nombre' => 'DIVISION DE INVESTIGACIONES Y FISCALIZACION DE SUSTANCIAS QUIMICAS', 'codigo' => '0064'],
            ['id' => '185', 'nombre' => 'DIVISION DE LABORATORIO QUIMICO', 'codigo' => '0103'],
            ['id' => '186', 'nombre' => 'DIVISION DE SEGURIDAD BANCARIA', 'codigo' => '0090'],
            ['id' => '187', 'nombre' => 'DIVISION DE SEGURIDAD INTEGRAL', 'codigo' => '0011'],
            ['id' => '188', 'nombre' => 'INSPECTORIA GENERAL', 'codigo' => '0005'],
            ['id' => '189', 'nombre' => 'OFICINA DE TECNOLOGIAS DE LA INFORMACION', 'codigo' => '0041']
        ];

        foreach ($unidades as $unidad) {
            UnidadAdministrativa::create([

                'id' => $unidad['id'],
                'nombre' => $unidad['nombre'],
                'codigo' => $unidad['codigo'],
            ]);
        }
    }
}
